# Generated by Django 5.0 on 2026-02-20 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("a", "Active"), ("i", "Inactive")],
                        db_index=True,
                        default="a",
                        max_length=1,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                ("run_id", models.CharField(max_length=100, unique=True)),
                ("environment", models.CharField(max_length=50)),
                ("build_id", models.CharField(max_length=100)),
                ("execution_time", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_on"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TestCaseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                ("test_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="FAILED",
                        max_length=20,
                    ),
                ),
                ("screenshot_path", models.TextField(blank=True, null=True)),
                ("video_path", models.TextField(blank=True, null=True)),
                ("trace_path", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("stack_trace", models.TextField(blank=True, null=True)),
                ("html", models.TextField()),
                ("symentic_dom", models.TextField()),
                ("page_url", models.TextField(blank=True, null=True)),
                ("failed_selector", models.TextField(blank=True, null=True)),
                ("execution_time", models.FloatField(blank=True, null=True)),
                ("embedding", models.JSONField(blank=True, null=True)),
                (
                    "test_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="test_analytics.testrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
                "abstract": False,
            },
        ),
    ]
