# Generated by Django 5.0 on 2026-02-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcaseresult",
            name="symentic_dom",
            field=models.TextField(blank=True, null=True),
        ),
    ]
