# Generated by Django 5.0 on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_analytics", "0002_alter_testcaseresult_symentic_dom"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcaseresult",
            name="failure_category",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="testcaseresult",
            name="healed_selector",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testcaseresult",
            name="healing_attempted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="testcaseresult",
            name="healing_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testcaseresult",
            name="healing_outcome",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="testcaseresult",
            name="root_cause",
            field=models.TextField(blank=True, null=True),
        ),
    ]
