# Generated by Django 5.0 on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_analytics", "0003_testcaseresult_failure_analytics_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcaseresult",
            name="step_events",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
