# Generated by Django 5.0 on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_analytics", "0004_testcaseresult_step_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcaseresult",
            name="history_assisted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="testcaseresult",
            name="history_hits",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="testcaseresult",
            name="ui_change_level",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="testcaseresult",
            name="validation_status",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
