# Generated by Django 5.0 on 2026-02-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_analytics", "0005_testcaseresult_healing_meta_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcaseresult",
            name="cache_fallback_to_fresh",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="testcaseresult",
            name="cache_hit",
            field=models.BooleanField(default=False),
        ),
    ]
