# Generated by Django 5.0 on 2026-02-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_analytics", "0008_state_remove_generation_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsDashboardLink",
            fields=[],
            options={
                "verbose_name": "Analytics Dashboard",
                "verbose_name_plural": "Analytics Dashboard",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("test_analytics.testrun",),
        ),
    ]
