# Generated by Django 5.0 on 2026-02-27 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UIPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("feature_name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("route",)},
            },
        ),
        migrations.CreateModel(
            name="UIRouteSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "snapshot_type",
                    models.CharField(
                        choices=[
                            ("BASELINE", "Baseline"),
                            ("NEW_STRUCTURE", "New Structure"),
                        ],
                        default="BASELINE",
                        max_length=20,
                    ),
                ),
                ("is_current", models.BooleanField(default=True)),
                ("dom_hash", models.CharField(max_length=64)),
                ("snapshot_json", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="ui_knowledge.uipage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UIElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selector", models.TextField()),
                ("tag", models.CharField(blank=True, max_length=30)),
                ("role", models.CharField(blank=True, max_length=50)),
                ("text", models.TextField(blank=True)),
                ("test_id", models.CharField(blank=True, max_length=100)),
                ("element_id", models.CharField(blank=True, max_length=100)),
                ("intent_key", models.CharField(default="generic", max_length=100)),
                ("stability_score", models.FloatField(default=1.0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="ui_knowledge.uiroutesnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UIChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("NO_CHANGE", "No Change"),
                            ("MINOR", "Minor Change"),
                            ("STRUCTURAL", "Structural Change"),
                        ],
                        max_length=20,
                    ),
                ),
                ("added_selectors", models.JSONField(default=list)),
                ("removed_selectors", models.JSONField(default=list)),
                ("auto_promoted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ui_knowledge.uipage",
                    ),
                ),
                (
                    "baseline_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baseline_changes",
                        to="ui_knowledge.uiroutesnapshot",
                    ),
                ),
                (
                    "new_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_changes",
                        to="ui_knowledge.uiroutesnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UIScreenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_path", models.TextField()),
                ("viewport", models.CharField(blank=True, max_length=50)),
                ("device", models.CharField(blank=True, max_length=50)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="ui_knowledge.uiroutesnapshot",
                    ),
                ),
            ],
        ),
    ]
