# Generated by Django 5.0 on 2026-07-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_analytics', '0002_client_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testrun',
            options={},
        ),
    ]
