# Generated by Django 5.0 on 2026-01-16 15:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], db_index=True, default='a', max_length=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('secret_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clientname', models.CharField(max_length=255)),
                ('client_logo', models.ImageField(null=True, upload_to='uploads/clientlogo/')),
            ],
            options={
                'verbose_name_plural': 'Manage Clients',
            },
        ),
    ]
