# Generated by Django 5.0 on 2026-07-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clients_llm_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, unique=True),
        ),
    ]
