# Generated by Django 5.0 on 2026-07-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0002_kind_cucumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnerjob',
            name='argv',
            field=models.JSONField(default=list, help_text='Command + args actually executed.'),
        ),
    ]
