"""
Django settings for flaky_healer project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env() -> None:
    """
    Minimal .env loader (no extra dependency required).
    Loads KEY=VALUE pairs into process env if key is not already set.
    """
    env_file = BASE_DIR / ".env"
    if not env_file.exists():
        return

    for raw in env_file.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


_load_local_env()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from env in production (Render sets DJANGO_SECRET_KEY via
# `generateValue: true` in render.yaml). The literal fallback keeps local
# dev working without any extra setup.
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-4)o(#a@@l#rsi$rp5un=7vo5vw%!x_%p_t49c^%)875735h&4)",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "true").strip().lower() in ("true", "1", "yes", "on")

# Read from env so ngrok / staging / production hostnames can be added
# without editing this file. Fallback to `["*"]` for local dev — same
# effective behaviour as the previous `[]` under DEBUG=True.
ALLOWED_HOSTS = [
    h.strip() for h in os.getenv("ALLOWED_HOSTS", "").split(",") if h.strip()
] or ["*"]

# Trusted origins for CSRF over HTTPS. Django requires these to be full
# scheme+host URLs (unlike ALLOWED_HOSTS). Build from ALLOWED_HOSTS, skipping
# the "*" wildcard (which Django rejects) and stripping any leading ".".
# Example: ALLOWED_HOSTS=".onrender.com" → CSRF_TRUSTED_ORIGINS=[
# "https://*.onrender.com"]. Users can override with CSRF_TRUSTED_ORIGINS in env.
_csrf_env = os.getenv("CSRF_TRUSTED_ORIGINS", "").strip()
if _csrf_env:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_env.split(",") if o.strip()]
else:
    CSRF_TRUSTED_ORIGINS = []
    for host in ALLOWED_HOSTS:
        if host == "*":
            continue
        if host.startswith("http://") or host.startswith("https://"):
            CSRF_TRUSTED_ORIGINS.append(host)
        elif host.startswith("."):
            CSRF_TRUSTED_ORIGINS.append(f"https://*{host}")
        else:
            CSRF_TRUSTED_ORIGINS.append(f"https://{host}")


# Application definition

INSTALLED_APPS = [
    "admin_interface",
    "colorfield",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'clients',
    'import_export',
    'rest_framework',
    'curertestai',
    'test_analytics',
    'test_generation',
    'ui_knowledge',
    # Phase 3 — dashboard absorbs Streamlit
    'django_q',
    'integrations_jira',
    'runners',
]
X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Whitenoise serves collectstatic output directly from the app process —
    # no CDN / S3 required. MUST come right after SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Phase 1 multi-tenant resolution: must run AFTER DRF authentication populates
    # request.auth, which it does at the view layer. The middleware's process_view
    # hook runs after that. See clients/middleware.py.
    'clients.middleware.ClientResolutionMiddleware',
]

ROOT_URLCONF = 'flaky_healer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'flaky_healer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Prefer DATABASE_URL when set (Render, staging, prod). Falls back to the
# dev MySQL block below when the env is unset — local Mac keeps working.
import dj_database_url  # requirements.txt: dj-database-url

_db_url = os.getenv("DATABASE_URL", "").strip()
if _db_url:
    DATABASES = {
        "default": dj_database_url.config(
            default=_db_url,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=(not DEBUG),
        ),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('MYSQL_DB', 'ai_healer_service'),
            'USER': os.getenv('MYSQL_USER', 'root'),
            'PASSWORD': os.getenv('MYSQL_PASSWORD', ''),
            'HOST': os.getenv('MYSQL_HOST', 'localhost'),
            'PORT': os.getenv('MYSQL_PORT', '3306'),
        },
    # # NEW PostgreSQL DB
    # "playwright": {
    #     "ENGINE": "django.db.backends.postgresql",
    #     "NAME": "playwright_artifacts",
    #     "USER": "xebia_ai",
    #     "PASSWORD": "@xebia_ai",
    #     "HOST": "localhost",
    #     "PORT": "5432",
    # }
}
# DATABASE_ROUTERS = [
#     "test_analytics.db_router.PlaywrightRouter"
# ]



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
# Whitenoise: compressed + manifest-hashed static files served straight from
# the gunicorn process. No CDN required. MIDDLEWARE order (WhiteNoise right
# after SecurityMiddleware) is enforced above.
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/uploads/"
MEDIA_ROOT = os.path.join(BASE_DIR, "uploads")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#rest_framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

#Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} | {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        # Phase 10 — was FileHandler(BASE_DIR/logs/auth.log). Render's
        # filesystem is ephemeral and read-only on container layers, so we
        # stream to stdout instead; Render's log aggregator captures it.
        # Dev still sees the same lines in the terminal.
        "file": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },

    "loggers": {
        "auth": {   # your app name
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# =====================================================================
# Phase 3 configuration
# =====================================================================

# Repository root (used by runners app to spawn `npm run ...` and `npx playwright`
# from the same cwd Streamlit used).
REPO_ROOT = os.path.abspath(os.path.join(BASE_DIR, "..", ".."))

# Fernet key for encrypting Jira API tokens at rest (integrations_jira app).
# In dev the key falls back to a deterministic value derived from SECRET_KEY so
# migrations do not fail. Override in production via the env var.
_FERNET_KEY = os.getenv("FERNET_KEY", "")
if not _FERNET_KEY:
    import base64, hashlib
    _FERNET_KEY = base64.urlsafe_b64encode(hashlib.sha256(SECRET_KEY.encode()).digest()).decode()
FERNET_KEY = _FERNET_KEY

# django-q2 broker configuration.
# Redis is preferred; the ORM broker is a zero-dep fallback for local hacking.
#
# Two ways to configure Redis:
#   * REDIS_URL (single connection string) — how Render's managed Redis
#     exposes credentials. Preferred in prod.
#   * Discrete REDIS_HOST / REDIS_PORT / REDIS_DB / REDIS_PASSWORD env vars —
#     easier for local dev where you already have Redis on localhost.
def _q_redis_config() -> dict:
    """Return the `redis` sub-dict for django-q2's Q_CLUSTER."""
    from urllib.parse import urlparse
    url = os.getenv("REDIS_URL", "").strip()
    if url:
        # rediss://:pass@host:port/db  (rediss = TLS; redis = plain)
        parsed = urlparse(url)
        return {
            "host": parsed.hostname or "127.0.0.1",
            "port": int(parsed.port or 6379),
            "db": int((parsed.path or "/0").lstrip("/") or 0),
            "password": parsed.password or None,
            "ssl": parsed.scheme == "rediss",
        }
    return {
        "host": os.getenv("REDIS_HOST", "127.0.0.1"),
        "port": int(os.getenv("REDIS_PORT", "6379")),
        "db": int(os.getenv("REDIS_DB", "0")),
        "password": os.getenv("REDIS_PASSWORD", "") or None,
        "ssl": os.getenv("REDIS_SSL", "false").lower() in ("true", "1", "yes"),
    }


Q_CLUSTER = {
    "name": "flaky_healer",
    "workers": int(os.getenv("Q_WORKERS", "2")),
    "recycle": 500,
    "timeout": int(os.getenv("Q_TIMEOUT", "3600")),  # 1 h upper bound per task
    "retry": int(os.getenv("Q_RETRY", "3700")),      # must be > timeout
    "compress": True,
    "save_limit": 1000,
    "queue_limit": 50,
    "cpu_affinity": 1,
    "label": "Django Q",
    "redis": _q_redis_config(),
}
if os.getenv("Q_ORM_BROKER", "false").lower() == "true":
    # Fallback broker for environments without Redis (development only).
    Q_CLUSTER.pop("redis", None)
    Q_CLUSTER["orm"] = "default"

# Runner log tail directory (one file per RunnerJob, appended by the worker,
# tailed by the SSE endpoint in the runners app).
RUNNER_LOG_DIR = os.path.join(BASE_DIR, "logs", "runners")
# Defensive: on Render the container filesystem can be read-only for parts
# of the tree; a permission error here would crash Django import. Runner
# logs are best-effort and ephemeral anyway.
try:
    os.makedirs(RUNNER_LOG_DIR, exist_ok=True)
except OSError:
    pass

# ---------------------------------------------------------------------------
# LLM configuration — Phase 1 of the robustness overhaul
# ---------------------------------------------------------------------------
# Every agent in `test_generation` routes through `llm_backends.py`. Ollama has
# been removed; OpenAI is the only backend. If OPENAI_API_KEY is unset the
# pipeline halts with a clear error at the first LLM call.
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "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")
# Tool-use kill-switch. Default "on" so the Root-Cause Fixer runs in
# tool-calling mode (Claude-Code-style loop over Playwright MCP + artifact
# tools). Set to "off" to revert to the legacy single-shot prompt path.
OPENAI_TOOL_USE = os.getenv("OPENAI_TOOL_USE", "on").lower() in ("on", "1", "true", "yes")

# ---------------------------------------------------------------------------
# Phase 6.1 — Jira report presentation
# ---------------------------------------------------------------------------
# When ON, the legacy attachment path re-runs alongside the rich ADF comment
# (page-object files + runner log tail as attachments). Default is OFF —
# post ONLY the beautifully-formatted ADF comment. Tenants that need raw
# files to ship can re-enable per-instance.
JIRA_REPORT_ATTACH_ARTIFACTS = os.getenv("JIRA_REPORT_ATTACH_ARTIFACTS", "off")

# Public-facing URL of this Django server. Used in Jira comments to link
# stakeholders back to the Jobs dashboard for full run details. Leave
# blank in dev; set to e.g. https://xt-forge.example.com in prod.
PUBLIC_BASE_URL = os.getenv("PUBLIC_BASE_URL", "http://127.0.0.1:8000")

# ---------------------------------------------------------------------------
# TypeScript normalizer — Phase 2 of the robustness overhaul
# ---------------------------------------------------------------------------
# `ast`   → shell out to the Node sidecar at
#           test_generation/ts_normalizer/index.mjs (ts-morph). Falls back to
#           regex on sidecar failure so the pipeline never gets stuck.
# `regex` → skip the sidecar entirely; use the legacy in-process regex
#           normalizer only.
# `both`  → run the sidecar first, then apply the regex normalizer on top.
#           Useful during rollout to catch regressions in the sidecar.
TS_NORMALIZER_MODE = os.getenv("TS_NORMALIZER_MODE", "ast").lower()
# Absolute path to the sidecar. Overridable for tests; default computed from
# BASE_DIR so nothing has to be hardcoded.
TS_NORMALIZER_SCRIPT = os.getenv(
    "TS_NORMALIZER_SCRIPT",
    str(BASE_DIR / "test_generation" / "ts_normalizer" / "index.mjs"),
)
# Node binary. Falls back to `node` on PATH.
TS_NORMALIZER_NODE_BIN = os.getenv("TS_NORMALIZER_NODE_BIN", "node")
# Hard timeout for a single sidecar invocation, in seconds.
TS_NORMALIZER_TIMEOUT_SECONDS = float(os.getenv("TS_NORMALIZER_TIMEOUT_SECONDS", "15"))

# ---------------------------------------------------------------------------
# Selector verifier — runs after Artifact stage, before Execute
# ---------------------------------------------------------------------------
# The verifier opens each seed URL via Playwright MCP, probes every locator
# in every generated page-object file, and asks a GPT-4o tool-using loop to
# rewrite ONLY the page-objects whose locators don't resolve. Reduces
# red-Execute-iteration repair rounds by catching selector misses at the
# source. Never blocks the Artifact stage response; returns a report the
# review panels render alongside the AST normalizer output.
SELECTOR_VERIFY_ENABLED = os.getenv("SELECTOR_VERIFY_ENABLED", "on")

# ---------------------------------------------------------------------------
# Phase 9.7 — require ground-truth ui_knowledge before Artifact stage
# ---------------------------------------------------------------------------
# When True (default) and the tenant has a base_url set, the Artifact stage
# 409s if no UIElement rows exist for the seed URLs. This prevents the LLM
# from inventing selectors like `[data-testid="logo-image"]` on tenants
# whose ui_knowledge just hasn't been synced yet. Set to `false` in .env to
# fall back to the pre-Phase-9 behaviour (LLM guesses when ground truth
# is missing).
XT_FORGE_REQUIRE_UI_KNOWLEDGE = os.getenv(
    "XT_FORGE_REQUIRE_UI_KNOWLEDGE", "true"
).strip().lower() not in {"false", "0", "no", "off", ""}

# ---------------------------------------------------------------------------
# Phase 5.1 — Auto-capture ui_knowledge before Artifact stage
# ---------------------------------------------------------------------------
# Before the artifact generator runs, we check ui_knowledge for a BASELINE
# snapshot per (client, route). If any seed URL is missing or the newest
# snapshot is older than MAX_AGE_DAYS, we crawl (via wraper-healer/crawlContext.mjs)
# and persist through ui_knowledge.persist_service.persist_snapshot.
#
# Kill-switch: set TEST_GEN_UI_KNOWLEDGE_AUTO_CAPTURE=off to disable the
# auto-capture entirely. In that mode the pipeline falls back to whatever
# ui_knowledge already has (may be empty), same behavior as before Phase 5.
TEST_GEN_UI_KNOWLEDGE_AUTO_CAPTURE = os.getenv("TEST_GEN_UI_KNOWLEDGE_AUTO_CAPTURE", "on")
TEST_GEN_UI_KNOWLEDGE_MAX_AGE_DAYS = int(os.getenv("TEST_GEN_UI_KNOWLEDGE_MAX_AGE_DAYS", "7"))
TEST_GEN_UI_KNOWLEDGE_CRAWL_TIMEOUT = int(os.getenv("TEST_GEN_UI_KNOWLEDGE_CRAWL_TIMEOUT", "240"))


# =====================================================================
# Phase 10 — HTTPS hardening (production only)
# =====================================================================
# Enabled when DEBUG=False (typical Render deployment). Trusts Render's
# X-Forwarded-Proto header so `request.is_secure()` returns True, then
# enforces HTTPS redirects and secure cookies. Dev on the Mac keeps
# working because DEBUG defaults to True there.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
