# Generated by Django 5.0 on 2026-01-23 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealerRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("a", "Active"), ("i", "Inactive")],
                        db_index=True,
                        default="a",
                        max_length=1,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                ("batch_id", models.IntegerField(default=0)),
                ("failed_selector", models.TextField()),
                ("html", models.TextField()),
                ("use_of_selector", models.TextField()),
                ("selector_type", models.CharField(max_length=20)),
                ("url", models.URLField()),
                ("healed_selector", models.TextField()),
                ("confidence", models.FloatField()),
                ("success", models.BooleanField(default=False)),
                ("processing_time_ms", models.IntegerField()),
                ("llm_used", models.BooleanField(default=False)),
                ("screenshot_analyzed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_on"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HealerRequestBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("a", "Active"), ("i", "Inactive")],
                        db_index=True,
                        default="a",
                        max_length=1,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                ("batch_id", models.IntegerField(default=0)),
                ("total_requests", models.IntegerField(default=0)),
                ("success", models.IntegerField(default=0)),
                ("failure", models.IntegerField(default=0)),
                ("processing_time_ms", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_on"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SuggestedSelector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("a", "Active"), ("i", "Inactive")],
                        db_index=True,
                        default="a",
                        max_length=1,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                ("selector", models.TextField()),
                ("score", models.FloatField()),
                ("base_score", models.FloatField()),
                ("attribute_score", models.FloatField()),
                ("tag", models.CharField(max_length=20)),
                ("text", models.TextField()),
                ("xpath", models.TextField()),
                (
                    "healer_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_selectors",
                        to="curertestai.healerrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
                "abstract": False,
            },
        ),
    ]
