# Generated by Django 5.0 on 2026-01-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curertestai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healerrequest',
            name='batch_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healerrequestbatch',
            name='batch_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
