# Generated by Django 5.0 on 2026-01-23 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curertestai", "0002_alter_healerrequest_batch_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healerrequestbatch",
            name="batch_id",
        ),
        migrations.AlterField(
            model_name="healerrequest",
            name="batch_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="healer_requests",
                to="curertestai.healerrequestbatch",
            ),
        ),
    ]
