# Generated by Django 5.0 on 2026-01-23 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curertestai", "0003_remove_healerrequestbatch_batch_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healerrequest",
            name="batch_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="healer_requests",
                to="curertestai.healerrequestbatch",
            ),
        ),
    ]
