# Generated by Django 5.0 on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curertestai", "0005_healerrequest_client_id_healerrequest_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="healerrequest",
            name="candidate_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healerrequest",
            name="dom_fingerprint",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="healerrequest",
            name="history_assisted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="healerrequest",
            name="history_hits",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="healerrequest",
            name="intent_key",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="healerrequest",
            name="ui_change_level",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="healerrequest",
            name="validation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healerrequest",
            name="validation_status",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
