# Generated by Django 5.0 on 2026-02-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("curertestai", "0006_healerrequest_history_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("a", "Active"), ("i", "Inactive")], db_index=True, default="a", max_length=1)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                ("page_url", models.URLField(db_index=True)),
                ("use_of_selector", models.TextField()),
                ("intent_key", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("failed_selector", models.TextField(blank=True, null=True)),
                ("healed_selector", models.TextField(blank=True, null=True)),
                ("dom_fingerprint", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("signature_tokens", models.JSONField(blank=True, null=True)),
                ("html_excerpt", models.TextField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("validation_status", models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "source_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dom_snapshots",
                        to="curertestai.healerrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
    ]
